import './globals.css'
import Link from 'next/link'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Treinamento',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <header>
          <h1>LOGO</h1>
          <h2>Sua Melhor Opção</h2>
          <nav>
          <Link href='/'>Início</Link>
          <Link href='/sobre'>Sobre</Link>
          <Link href='/contato'>Contato</Link>
          </nav>
        </header>
        {children}
        <footer>
        <h2>BrasilCard</h2>
          <p>Seu Parceiro de negócios</p>
          <nav>
          <Link href='/'>Início</Link>
          <Link href='/sobre'>Sobre</Link>
          <Link href='/contato'>Contato</Link>
          </nav>
        </footer>
        </body>
    </html>
  )
}
